language: node_js

node_js: "5.1"

install:
  - npm install -g yarn
  - yarn

# cache:
#   directories:
#     - $TRAVIS_BUILD_DIR/node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # - npm start &
  # - sleep 5

script: $TRAVIS_BUILD_DIR/.travis.sh

sudo: required
