export const Checkmark = require('svg/checkmark.svg')
export const Delete = require('svg/android-delete.svg')
export const Close = require('svg/ios-close-empty.svg')
export const Reply = require('svg/reply.svg')
export const Add = require('svg/add.svg')
export const DeleteForever = require('svg/delete-forever.svg')
export const Play = require('svg/play.svg')
export const Sort = require('svg/sort.svg')
