export { default as Checkmark } from 'svg/checkmark.svg'
export { default as Delete } from 'svg/android-delete.svg'
export { default as Close } from 'svg/ios-close-empty.svg'
export { default as Reply } from 'svg/reply.svg'
export { default as Add } from 'svg/add.svg'
export { default as DeleteForever } from 'svg/delete-forever.svg'
export { default as Play } from 'svg/play.svg'
export { default as Sort } from 'svg/sort.svg'
